### ISSUE TITLE
Add a "tests_requires" 

### ISSUE THREAD

**Issue by hadware** [DrMarc/slab#21]
Hey, first issue for my review of this really cool package :)

Could you add a `tests_require` requires to your `setup.py` (and maybe migrate the stuff that's in `extra_requires -> "testing"` to it). You should probably also add `pytest` as a test dependency since it seems that it's your testing framework.

It makes things easier for testing, as we can then just run `python setup.py test`, then run the tests.

On a side note: are you fine with me posting small issues (very much like this one) that could potentially be mostly nitpicking about stuff, or would you prefer that I only stick strictly to issues about what's required to pass the "JOSS bar"?

**Comment by DrMarc** [comment]
Hi,

Good point,  we'll add pytest to the requirements. My understanding of setuptools is that `tests_require` is deprecated and the recommended way to specify additional dependencies is through `extras_require` (see https://setuptools.readthedocs.io/en/latest/userguide/keywords.html).
You can use `pip install slab[testing]` instead of `pip install slab test` - I'll mention that in the installation instructions.

Yes, small issues are fine - very helpful!

**Comment by DrMarc** [comment]
Resolved in f509c43.

**Comment by hadware** [comment]
Ah! well, paint me astonished, i didn't know it was deprecated. I'll also change that on my own packages :thinking:
