### ISSUE TITLE
[BUG in Signal.__add__]

### ISSUE THREAD

**Issue by sneakers-the-rat** [DrMarc/slab#23]
**Describe the bug**

Sounds of different durations can't be added together

**To Reproduce**

```python
import slab
tone = slab.Sound.tone(frequency=500, duration=0.5)
noise = slab.Sound.pinknoise(duration=0.3)
stim = tone + noise
```

yields

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/jonny/git/slab/slab/signal.py", line 97, in __add__
    new.data = self.data + other.data
ValueError: operands could not be broadcast together with shapes (4000,1) (2400,1) 
```

**Expected behaviour**

Probably should zero-pad the shorter array. one pretty hacky method that i didn't test

```python
if self.data.shape[0]<other.data.shape[0]:
    new.data = np.pad(self.data, (0,other.data.shape[0]-self.data.shape[0]), 'constant', constant_values=(0,0))
elif self.data.shape[0]>other.data.shape[0]:
      new.data = np.pad(other.data, (0,self.data.shape[0]-other.data.shape[0]), 'constant', constant_values=(0,0))
else:
    new.data = self.data + other.data

```

**Comment by hadware** [comment]
Maybe the "+" operator should be kept for same length `Sounds` and the `Signal` class (from which `Sound` inherits) could have a separate method such as `Signal.add(other: Signal, autopad: bool = True, position: Literal["left", "center", "right"] = "center")` that could be used when users are willing to add two objects of different lengths.

Having a silent "autopadding" is a tricky question, since this library is aimed to be used by students (and thus, beginners):
- on the one hand it's good that they shouldn't be worrying about sound lenghts
- on the other hand if the library does this kind of stuff "behind their backs" it could confuse them a lot
that's on @DrMarc  to decide

IMHO, the "+" operator should be strict (no adding of different lengths signals), but raise a clearer error, such as this

```python
ValueError: Could not add two Signals of different lengths, use Signal.add to do so
```
which would force the user to more explicitly define the behavior they desire.

**Comment by OleBialas** [comment]
I agree with @hadware - there should not be silent autopadding. Since the `Signal` class has a `.resize` method it be might be enough to raise an error like:
```python
ValueError: Could not add two Signals of different lengths, use Signal.resize to change the length.
```

**Comment by DrMarc** [comment]
Hi, good point. This is a question of software architecture. From my side, the current behaviour is exactly as intended. Arithmetic operators in signal objects and their descendants are passed to the `.data` numpy array and you get numpy's error messages when something goes wrong. So far, we found this to be transparent and easy to understand for anyone familiar with numpy. The same happens when subtracting, multiplying, etc., sounds of different length. Autopadding may not lead to the intended results in most cases. I agree that adding two sounds is a common scenario, but you'd still have to be explicit about when your tone should start in the noise (to use the example above). Padding or positioning a sound within a longer one is trivial (`.resize`, `.sequence`, `.silence`, `.envelope`), but has to done explicitly when constructing a stimulus.

**Comment by sneakers-the-rat** [comment]
fair points, you convinced me :). giving a more informative error message sounds good to me!
