### ISSUE TITLE
Have Signal object be displayable in jupyter notebooks

### ISSUE THREAD

**Issue by hadware** [DrMarc/slab#27]
A pretty cool feature i've seen in `pyannote.core` (partially unrelated) is that its primitives are "immediately" displayable in jupyter notebooks (just "showing" an object in a cell activates its matplotlib representation). 

This could be pretty useful in slab's case, where displaying Signals and Sounds could make it much intuitive to use. Moreover, most of the display code seems to be already there, if I'm not mistaken, it's mostly pipe-work to implement it.

Here's how it's done:
https://github.com/pyannote/pyannote-core/blob/635bb0eb229aa406606c22792082754a3828d952/pyannote/core/timeline.py#L1124

**Comment by DrMarc** [comment]
This is a nice idea. I went ahead and implemented `_repr_png_()` and `repr_svg_()` for the signal class to try it out. Playing around with it in Jupyter showed that it was not all that useful (see screenshot below), because a static plot of all samples does not show much (channels, samplerate, does ist start and end with zeros, etc.). It would also mean that the console and the notebook show very different representations of the object, and thus any tutorial (and the docs) would need to differentiate between the two.
However, the current '__repr__()' prints ugly in a notebook. My suggestion would be to add an HTML representation that pretty-prints the same info in a notebook.
<img width="706" alt="screenshot" src="https://user-images.githubusercontent.com/7555727/118391490-d69b7900-b634-11eb-9a9f-75c1dcea164e.png">

**Comment by DrMarc** [comment]
The new `_repr_html_` method pretty-prints sample info for signals (and all descendants):
<img width="388" alt="screenshot2" src="https://user-images.githubusercontent.com/7555727/118402875-221d4980-b66c-11eb-8566-db6e89014a7a.png">
